import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 6, y = 4 }
decorations = "buttonless"
opacity = 0.66
blur = true
startup_mode = "SimpleFullscreen"

[font]
# normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 15
# offset = { y = 12 }
# glyph_offset = { y = 6 }
# builtin_box_drawing = false

[cursor]
style = { shape = "Underline", blinking = "Always" }

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
