"$schema" = "https://starship.rs/config-schema.json"

format = """
$os\
$directory\
$git_branch\
$git_status\
$golang\
$nodejs\
$terraform\
$python\
$docker_context\
$cmd_duration\
$character"""

palette = "catppuccin_mocha"
add_newline = false

[os]
disabled = false
format = "[$symbol ](fg:peach)"

[directory]
format = "[$path ](fg:blue)"
truncate_to_repo = false
truncation_length = 6

[git_branch]
symbol = ""
format = "[($symbol $branch )](fg:green)"

[git_status]
format = "[($all_status$ahead_behind )](fg:flamingo)"

[nodejs]
symbol = ""
format = "[($symbol )](fg:teal)"

[golang]
symbol = ""
format = "[($symbol )](fg:sapphire)"

[python]
symbol = ""
format = "[($symbol )](fg:blue)"

[terraform]
symbol = "󱁢"
format = "[($symbol )](fg:purple)"

[docker_context]
symbol = ""
format = "[($symbol )](fg:sky)"

[cmd_duration]
min_time = 1000
format="[($duration )](fg:flamingo)"
show_milliseconds = false

[character]
success_symbol = "[](bold fg:lavender) "
error_symbol = "[✗](bold fg:red) "
vimcmd_symbol = "[](bold fg:creen)"
vimcmd_replace_one_symbol = "[](bold fg:purple)"
vimcmd_replace_symbol = "[](bold fg:purple)"
vimcmd_visual_symbol = "[](bold fg:lavender)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
purple = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = ""
Manjaro = ""
Mint = "󰣭"
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"
