git:
  paging:
    colorArg: always
    pager: delta --features catppuccin-mocha --paging=never --tabs=2

gui:
  nerdFontsVersion: '3'
  showRandomTip: false
  showDivergenceFromBaseBranch: arrowAndNumber
  showFileIcons: false
  sidePanelWidth: 0.21

  authorColors:
    '*': '#b4befe'
  theme:
    activeBorderColor:
      - '#b4befe'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#b4befe'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
